(function(root,factory){
  'use strict';
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.POKEMON_SLEEP_WEEKLY_PLANNER=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';

  const STORAGE_KEY='pokemon-sleep-weekly-plan-v1';
  const RECIPE_LEVEL_MULTIPLIER=3.03;
  const ACTIVITY_PROFILES=Object.freeze({
    normal:{label:'普通周',cookingMultiplier:1,carryBonus:0,note:'无活动临时加成。'},
    snapshot:{label:'迷你糖果增强周',cookingMultiplier:1,carryBonus:0,note:'当前 Mini Candy Boost 周不提供料理能量或产量倍率。'},
    mewtwo1:{label:'超梦登场活动·第1周',cookingMultiplier:1,carryBonus:8,psychicSkillBonus:2,note:'仅萌绿之岛／萌绿之岛 EX：全员持有上限＋8，超能力属性主技能等级＋2。超能力技能手的队伍排序会获得启发式加权。'},
    mewtwo2:{label:'超梦登场活动·第2周',cookingMultiplier:1,carryBonus:15,psychicSkillBonus:5,note:'仅萌绿之岛／萌绿之岛 EX：全员持有上限＋15，超能力属性主技能等级＋5。超梦睡眠×1.3及超大芒芒果的随机机制不计入固定产量。'},
    cooking125:{label:'料理能量＋25%',cookingMultiplier:1.25,carryBonus:0,note:'料理最终能量按 1.25 倍估算。'},
    cooking150:{label:'料理能量＋50%',cookingMultiplier:1.5,carryBonus:0,note:'料理最终能量按 1.50 倍估算。'},
    custom:{label:'自定义料理倍率',cookingMultiplier:1,carryBonus:0,note:'按下方输入的自定义料理倍率估算。'}
  });
  const STRATEGY_WEIGHTS=Object.freeze({balanced:{island:.58,cooking:.42,label:'均衡'},energy:{island:.84,cooking:.16,label:'树果／能量优先'},cooking:{island:.25,cooking:.75,label:'料理优先'}});
  const MEAL_NAMES=Object.freeze(['早餐','午餐','晚餐']);
  const DAY_NAMES=Object.freeze(['周一','周二','周三','周四','周五','周六','周日']);
  const clamp=(value,min,max)=>Math.min(max,Math.max(min,Number(value)||0));
  const round=(value,digits=1)=>{const scale=10**digits;return Math.round((Number(value)+Number.EPSILON)*scale)/scale};
  const readJson=(storage,key,fallback)=>{try{const value=storage&&storage.getItem(key);return value?JSON.parse(value):fallback}catch(_error){return fallback}};
  const writeJson=(storage,key,value)=>{try{storage&&storage.setItem(key,JSON.stringify(value));return true}catch(_error){return false}};
  function effectivePot(base,goodCamp){return Math.floor(clamp(Math.round(base),1,1000)*(goodCamp?1.5:1))}
  function recipeRows(recipes,type,pot){return (recipes||[]).filter(recipe=>recipe.energy>0&&recipe.total<=pot&&(!type||type==='全部'||recipe.type===type)).sort((a,b)=>b.energy-a.energy||a.total-b.total)}
  function chooseTargetRecipe(recipes,type,pot,daily={},inventory={}){
    const candidates=recipeRows(recipes,type,pot);if(!candidates.length)return null;
    return candidates.map(recipe=>{const coverage=recipe.ingredients.reduce((sum,item)=>sum+Math.min(1,((Number(daily[item.name])||0)*7+(Number(inventory[item.name])||0))/(item.amount*21)),0)/Math.max(1,recipe.ingredients.length);return {recipe,coverage,score:recipe.energy*(.35+.65*coverage)}}).sort((a,b)=>b.score-a.score||b.recipe.energy-a.recipe.energy)[0].recipe;
  }
  function individualIngredientProduction(mon,planner,production,goodCamp,carryBonus){
    const copy=carryBonus?{...mon,inv:String((Number(mon.inv)||0)+carryBonus)}:mon,result=planner.calculateTeam([copy],production,{goodCamp,energyProfile:'average'}),member=result.members[0],daily={};
    if(member)member.ingredients.forEach(item=>{daily[item.name]=(daily[item.name]||0)+item.perDay});return {daily,member};
  }
  function coverageScore(daily,targetRecipe){
    if(!targetRecipe||!targetRecipe.ingredients.length)return 0;
    return targetRecipe.ingredients.reduce((sum,item)=>sum+Math.min(1,(Number(daily[item.name])||0)/(item.amount*3)),0)/targetRecipe.ingredients.length*100;
  }
  function buildTeam(options){
    const {pokemon,context,recommendTeams,individualProductionScore,isFullTeamHealer,isSpecialPokemon,planner,production,goodCamp,activity,targetRecipe,strategy='balanced'}=options,eligible=pokemon.filter(mon=>mon.battleEligible!==false),weights=STRATEGY_WEIGHTS[strategy]||STRATEGY_WEIGHTS.balanced,regular=recommendTeams(context).regular;
    const eventArea=/萌绿之岛/.test(String(context.island&&context.island.name||'')),carryBonus=activity.psychicSkillBonus&&!eventArea?0:activity.carryBonus,activityOutput=mon=>{const base=individualProductionScore(mon,context),psychic=eventArea&&activity.psychicSkillBonus&&mon.berry==='芒芒果',bonus=psychic?(mon.specialty==='skill'?.045:.012)*activity.psychicSkillBonus:0;return base*(1+bonus)},islandValues=eligible.map(activityOutput),maxIsland=Math.max(...islandValues,1),healers=eligible.filter(isFullTeamHealer).sort((a,b)=>activityOutput(b)-activityOutput(a)),healer=healers.find(mon=>!isSpecialPokemon(mon.id))||healers[0]||null;
    const candidates=eligible.filter(mon=>!isFullTeamHealer(mon)&&!isSpecialPokemon(mon.id)).map(mon=>{const ingredient=individualIngredientProduction(mon,planner,production,goodCamp,carryBonus),island=activityOutput(mon)/maxIsland*100,cooking=coverageScore(ingredient.daily,targetRecipe),score=island*weights.island+cooking*weights.cooking;return {mon,ingredient,island,cooking,score}}).sort((a,b)=>b.score-a.score);
    const selected=[...candidates.slice(0,healer?4:5).map(row=>row.mon),...(healer?[healer]:[])];
    while(selected.length<5){const fallback=eligible.find(mon=>!selected.includes(mon)&&!isSpecialPokemon(mon.id));if(!fallback)break;selected.push(fallback)}
    const productionResult=planner.calculateTeam(selected.map(mon=>carryBonus?{...mon,inv:String((Number(mon.inv)||0)+carryBonus)}:mon),production,{goodCamp,energyProfile:'average'}),daily=Object.fromEntries(productionResult.ingredients.map(item=>[item.name,item.perDay]));
    return {members:selected,production:productionResult,daily,regular,weights,candidateRows:candidates,eventArea,carryBonus};
  }
  function canCook(recipe,stock){return recipe.ingredients.every(item=>(stock[item.name]||0)+1e-8>=item.amount)}
  function consume(recipe,stock){recipe.ingredients.forEach(item=>{stock[item.name]=Math.max(0,(stock[item.name]||0)-item.amount)})}
  function simulateMeals(options){
    const {recipes,type,pot,daily={},inventory={},cookingMultiplier=1}=options,candidates=recipeRows(recipes,type,pot),stock={...inventory},meals=[];let normalEnergy=0,expectedEnergy=0;
    for(let index=0;index<21;index++){
      Object.entries(daily).forEach(([name,amount])=>{stock[name]=(stock[name]||0)+amount/3});
      const recipe=candidates.find(item=>canCook(item,stock))||null,day=Math.floor(index/3),critFactor=day===6?1.6:1.1,energy=recipe?recipe.energy*RECIPE_LEVEL_MULTIPLIER*cookingMultiplier:0;
      if(recipe)consume(recipe,stock);normalEnergy+=energy;expectedEnergy+=energy*critFactor;meals.push({index,day,dayName:DAY_NAMES[day],mealName:MEAL_NAMES[index%3],recipe,normalEnergy:round(energy),expectedEnergy:round(energy*critFactor),critFactor});
    }
    return {meals,remaining:stock,normalEnergy:round(normalEnergy),expectedEnergy:round(expectedEnergy),cooked:meals.filter(meal=>meal.recipe).length};
  }
  function targetShortages(recipe,daily,inventory,mealCount=21){
    if(!recipe)return [];return recipe.ingredients.map(item=>{const need=item.amount*mealCount,available=(Number(daily[item.name])||0)*7+(Number(inventory[item.name])||0);return {name:item.name,need,available:round(available),shortage:round(Math.max(0,need-available)),perMeal:item.amount}}).sort((a,b)=>b.shortage-a.shortage);
  }
  function switchSuggestions(shortages,candidates){
    return shortages.filter(item=>item.shortage>0).map(item=>{const producers=candidates.map(row=>({mon:row.mon,perDay:Number(row.ingredient.daily[item.name])||0})).filter(row=>row.perDay>0).sort((a,b)=>b.perDay-a.perDay),best=producers[0],days=best?item.shortage/best.perDay:Infinity;return {ingredient:item.name,shortage:item.shortage,producer:best&&best.mon,perDay:best&&round(best.perDay),days:Number.isFinite(days)?round(Math.min(7,days),1):null,text:best?`前 ${Math.max(1,Math.ceil(Math.min(7,days)))} 天优先上场 #${best.mon.id} ${best.mon.name}，库存补到约 ${Math.ceil(item.perMeal*3)} 后再切回岛屿输出位。`:'当前盒子没有已解锁的稳定产手，建议依靠库存或下调食谱。'};});
  }
  function calculatePlan(options){
    const activityBase=ACTIVITY_PROFILES[options.activityKey]||ACTIVITY_PROFILES.normal,activity={...activityBase,cookingMultiplier:options.activityKey==='custom'?clamp(options.customCookingMultiplier,.1,5):activityBase.cookingMultiplier},pot=effectivePot(options.basePot,options.goodCamp),emptyDaily={},targetFirst=chooseTargetRecipe(options.recipes,options.recipeType,pot,emptyDaily,options.inventory),team=buildTeam({...options,activity,targetRecipe:targetFirst}),targetRecipe=chooseTargetRecipe(options.recipes,options.recipeType,pot,team.daily,options.inventory),finalTeam=targetRecipe&&targetRecipe.id!==targetFirst?.id?buildTeam({...options,activity,targetRecipe}):team,meals=simulateMeals({recipes:options.recipes,type:options.recipeType,pot,daily:finalTeam.daily,inventory:options.inventory,cookingMultiplier:activity.cookingMultiplier}),shortages=targetShortages(targetRecipe,finalTeam.daily,options.inventory),switches=switchSuggestions(shortages,finalTeam.candidateRows);return {activity,pot,targetRecipe,team:finalTeam,meals,shortages,switches};
  }
  function defaults(ingredients){return {islandIndex:0,berries:[],recipeType:'咖喱／浓汤',activityKey:'snapshot',customCookingMultiplier:1,goodCamp:true,basePot:81,strategy:'balanced',inventory:Object.fromEntries(ingredients.map(name=>[name,0]))}}
  function normalizeState(value,ingredients,islandCount){const base=defaults(ingredients),source=value&&typeof value==='object'?value:{},recipeType=['咖喱／浓汤','沙拉','点心／饮料','全部'].includes(source.recipeType)?source.recipeType:base.recipeType,activityKey=Object.hasOwn(ACTIVITY_PROFILES,source.activityKey)?source.activityKey:base.activityKey,strategy=Object.hasOwn(STRATEGY_WEIGHTS,source.strategy)?source.strategy:base.strategy;return {...base,...source,recipeType,activityKey,strategy,goodCamp:source.goodCamp!==false,basePot:clamp(Math.round(source.basePot||base.basePot),1,1000),customCookingMultiplier:clamp(source.customCookingMultiplier||1,.1,5),islandIndex:clamp(Math.round(source.islandIndex),0,Math.max(0,islandCount-1)),inventory:{...base.inventory,...(source.inventory&&typeof source.inventory==='object'?source.inventory:{})}}}
  function mount(options={}){
    if(typeof document==='undefined')return null;const rootNode=document.querySelector('#weeklyPlanner');if(!rootNode)return null;
    let browserStorage=null;try{browserStorage=window.localStorage}catch(_error){}
    const pokemon=options.pokemon||[],islands=options.islands||[],recipes=options.recipes||[],ingredients=options.ingredients||[],storage=options.storage||browserStorage,teamPlanner=options.teamPlanner,production=options.production&&options.production.byBoxId||options.production||{};
    const controls={island:document.querySelector('#weeklyIsland'),berries:document.querySelector('#weeklyBerries'),recipeType:document.querySelector('#weeklyRecipeType'),activity:document.querySelector('#weeklyActivity'),custom:document.querySelector('#weeklyCustomMultiplier'),camp:document.querySelector('#weeklyGoodCamp'),pot:document.querySelector('#weeklyPot'),strategy:document.querySelector('#weeklyStrategy'),inventory:document.querySelector('#weeklyInventory'),generate:document.querySelector('#weeklyGenerate'),result:document.querySelector('#weeklyResult'),stamp:document.querySelector('#weeklySaveStamp')};
    let state=normalizeState(readJson(storage,STORAGE_KEY,{}),ingredients,islands.length);
    islands.forEach((island,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=island.name;controls.island.append(option)});Object.entries(ACTIVITY_PROFILES).forEach(([key,item])=>{const option=document.createElement('option');option.value=key;option.textContent=item.label;controls.activity.append(option)});
    function selectedBerries(){const island=islands[state.islandIndex],selects=[...controls.berries.querySelectorAll('select')];return selects.length?selects.map(select=>select.value):island.defaultBerries||String(island.berries||'').split('／')}
    function renderBerryControls(){const island=islands[state.islandIndex];controls.berries.replaceChildren();if(!island.berryMode){controls.berries.hidden=true;return}controls.berries.hidden=false;const current=Array.isArray(state.berries)&&state.berries.length===3?state.berries:[...(island.defaultBerries||[])],all=options.allBerries||[];['树果 1','树果 2','树果 3'].forEach((label,index)=>{const wrap=document.createElement('label');wrap.textContent=island.kind==='EX'&&index===0?'主树果':label;const select=document.createElement('select'),allowed=island.berryMode==='cyan-expert'&&index===0?['橙橙果','桃桃果','椰木果']:all;allowed.forEach(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;select.append(option)});select.value=current[index]||allowed[index]||allowed[0];select.addEventListener('change',()=>{state.berries=selectedBerries();persist();render()});wrap.append(select);controls.berries.append(wrap)});state.berries=selectedBerries()}
    function renderInventory(){controls.inventory.replaceChildren();ingredients.forEach(name=>{const label=document.createElement('label'),input=document.createElement('input');label.textContent=name;input.type='number';input.min='0';input.step='1';input.inputMode='numeric';input.value=String(Number(state.inventory[name])||0);input.dataset.ingredient=name;input.addEventListener('change',()=>{state.inventory[name]=Math.max(0,Number(input.value)||0);persist()});label.append(input);controls.inventory.append(label)})}
    function syncControls(){controls.island.value=String(state.islandIndex);controls.recipeType.value=state.recipeType;controls.activity.value=state.activityKey;controls.custom.value=String(state.customCookingMultiplier);controls.custom.closest('.weekly-field').hidden=state.activityKey!=='custom';controls.camp.checked=Boolean(state.goodCamp);controls.pot.value=String(state.basePot);controls.strategy.value=state.strategy;renderBerryControls();renderInventory()}
    function persist(){writeJson(storage,STORAGE_KEY,state);controls.stamp.textContent=`已保存 · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`;window.dispatchEvent(new CustomEvent('pokemon-sleep:local-change',{detail:{type:'weekly-plan'}}))}
    function context(){const island=islands[state.islandIndex];return {island,index:state.islandIndex,berries:selectedBerries(),expert:island.kind==='EX'}}
    function icon(name){const api=window.POKEMON_SLEEP_INGREDIENTS;return api&&api.create?api.create(name,{label:name}):document.createTextNode(name)}
    function render(){
      if(!pokemon.length||!islands.length)return;const report=calculatePlan({pokemon,context:context(),recommendTeams:options.recommendTeams,individualProductionScore:options.individualProductionScore,isFullTeamHealer:options.isFullTeamHealer,isSpecialPokemon:options.isSpecialPokemon,planner:teamPlanner,production,goodCamp:state.goodCamp,activityKey:state.activityKey,customCookingMultiplier:state.customCookingMultiplier,recipes,recipeType:state.recipeType,basePot:state.basePot,strategy:state.strategy,inventory:state.inventory});controls.result.replaceChildren();
      const activityNote=report.activity.psychicSkillBonus&&!report.team.eventArea?`${report.activity.note} 当前选择的岛屿不在活动区域，因此本页没有套用持有与超能力技能加成。`:report.activity.note,overview=document.createElement('section');overview.className='weekly-overview';overview.innerHTML=`<div><span>本周目标食谱</span><h3>${report.targetRecipe?report.targetRecipe.name:'当前锅容量无可用食谱'}</h3><p>${activityNote}</p></div><div class="weekly-overview-stats"><span><small>有效锅容量</small><b>${report.pot}</b></span><span><small>预计完成</small><b>${report.meals.cooked}/21 餐</b></span><span><small>料理期望能量</small><b>${Math.round(report.meals.expectedEnergy).toLocaleString('zh-CN')}</b></span><span><small>建议收菜</small><b>${teamPlanner.formatHours(report.team.production.collectionHours)}</b></span></div>`;
      const team=document.createElement('section');team.className='weekly-section';team.innerHTML='<div class="weekly-section-head"><div><span>WEEK TEAM</span><h3>推荐周队伍</h3></div><small>默认保留全体回复位；其余按岛屿与料理策略加权</small></div>';const teamGrid=document.createElement('div');teamGrid.className='weekly-team';report.team.members.forEach((mon,index)=>{const card=document.createElement('article');card.innerHTML=`<span>位置 ${index+1}</span><b>#${mon.id} ${mon.name}</b><small>Lv.${mon.lv} · ${mon.specialtyLabel||''}</small>`;teamGrid.append(card)});const teamNote=document.createElement('p');teamNote.className='weekly-method';teamNote.textContent=`${STRATEGY_WEIGHTS[state.strategy].label}：岛屿产能 ${Math.round(report.team.weights.island*100)}%＋目标食谱覆盖 ${Math.round(report.team.weights.cooking*100)}%。${report.team.regular&&report.team.regular.ids?' 岛屿页无特殊宝可梦基准队仍可作为纯能量备选。':''}`;team.append(teamGrid,teamNote);
      const ingredientSection=document.createElement('section');ingredientSection.className='weekly-section';ingredientSection.innerHTML='<div class="weekly-section-head"><div><span>INGREDIENT FLOW</span><h3>每日食材与缺口</h3></div></div>';const ingredientGrid=document.createElement('div');ingredientGrid.className='weekly-ingredients';const relevant=[...new Set([...(report.targetRecipe?.ingredients||[]).map(item=>item.name),...Object.entries(report.team.daily).filter(([,amount])=>amount>.05).map(([name])=>name)])];relevant.forEach(name=>{const item=document.createElement('article'),short=report.shortages.find(row=>row.name===name);item.append(icon(name));const values=document.createElement('div');values.innerHTML=`<b>${round(report.team.daily[name]||0,1)} / 日</b><small>${short?(short.shortage>0?`目标差 ${short.shortage}`:`21餐足够`):'额外食材'}</small>`;item.append(values);ingredientGrid.append(item)});ingredientSection.append(ingredientGrid);
      const mealSection=document.createElement('section');mealSection.className='weekly-section';mealSection.innerHTML='<div class="weekly-section-head"><div><span>21 MEALS</span><h3>七日料理安排</h3></div><small>每天按当前队伍产量补入库存后再排餐</small></div>';const mealTable=document.createElement('div');mealTable.className='weekly-meals';for(let day=0;day<7;day++){const row=document.createElement('article'),dayMeals=report.meals.meals.filter(meal=>meal.day===day);row.innerHTML=`<strong>${DAY_NAMES[day]}</strong>`;dayMeals.forEach(meal=>{const cell=document.createElement('span');cell.innerHTML=`<small>${meal.mealName}</small><b>${meal.recipe?meal.recipe.name:'拌拌料理／缺材'}</b>`;row.append(cell)});mealTable.append(row)}mealSection.append(mealTable);
      const switchSection=document.createElement('section');switchSection.className='weekly-section';switchSection.innerHTML='<div class="weekly-section-head"><div><span>SWITCH TIMING</span><h3>换人时间与准备</h3></div></div>';const switchList=document.createElement('div');switchList.className='weekly-switches';if(report.switches.length)report.switches.forEach(item=>{const row=document.createElement('p');row.append(icon(item.ingredient),document.createTextNode(`：${item.text}`));switchList.append(row)});else{const row=document.createElement('p');row.textContent='按当前库存与估算产量，目标食谱没有硬缺口；整周可优先保持岛屿输出队。';switchList.append(row)}switchSection.append(switchList);
      controls.result.append(overview,team,ingredientSection,mealSection,switchSection);return report;
    }
    controls.island.addEventListener('change',()=>{state.islandIndex=Number(controls.island.value);state.berries=[];renderBerryControls();persist();render()});controls.recipeType.addEventListener('change',()=>{state.recipeType=controls.recipeType.value;persist();render()});controls.activity.addEventListener('change',()=>{state.activityKey=controls.activity.value;controls.custom.closest('.weekly-field').hidden=state.activityKey!=='custom';persist();render()});controls.custom.addEventListener('change',()=>{state.customCookingMultiplier=clamp(controls.custom.value,.1,5);persist();render()});controls.camp.addEventListener('change',()=>{state.goodCamp=controls.camp.checked;persist();render()});controls.pot.addEventListener('change',()=>{state.basePot=clamp(Math.round(controls.pot.value),1,1000);persist();render()});controls.strategy.addEventListener('change',()=>{state.strategy=controls.strategy.value;persist();render()});controls.generate.addEventListener('click',()=>{persist();render()});syncControls();render();return {render,getState:()=>({...state}),calculatePlan};
  }
  return Object.freeze({STORAGE_KEY,RECIPE_LEVEL_MULTIPLIER,ACTIVITY_PROFILES,STRATEGY_WEIGHTS,effectivePot,recipeRows,chooseTargetRecipe,individualIngredientProduction,coverageScore,buildTeam,simulateMeals,targetShortages,switchSuggestions,calculatePlan,normalizeState,mount});
});
