'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const projectRoot = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(projectRoot, 'index.html'), 'utf8');
const pokemonManagerSource = fs.readFileSync(path.join(projectRoot, 'pokemon-manager.js'), 'utf8');
const levelManagerSource = fs.readFileSync(path.join(projectRoot, 'level-manager.js'), 'utf8');
const pokemonManagerCss = fs.readFileSync(path.join(projectRoot, 'pokemon-manager.css'), 'utf8');
const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map(match => match[1]);
const duplicateIds = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))];
assert.deepStrictEqual(duplicateIds, [], `存在重复 id：${duplicateIds.join('、')}`);

const localRefs = [...html.matchAll(/(?:src|href)="([^"]+)"/g)]
  .map(match => match[1])
  .filter(ref => !/^(?:https?:|data:|#|mailto:|javascript:)/i.test(ref))
  .map(ref => ref.replace(/^\.\//, '').split(/[?#]/)[0]);
const missingRefs = [...new Set(localRefs)].filter(ref => !fs.existsSync(path.join(projectRoot, ref)));
assert.deepStrictEqual(missingRefs, [], `缺少本地资源：${missingRefs.join('、')}`);

const inlineScripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match => match[1]).filter(Boolean);
inlineScripts.forEach((source, index) => new vm.Script(source, { filename: `index-inline-${index}.js` }));
assert.ok(!html.includes('id="currentTeamIslandBonus"'), '当前队伍页不应再保留会与个人设置冲突的岛屿加成输入');
assert.ok(html.includes('id="currentTeamDuration"'), '当前队伍页缺少纯能量计算时长输入');
assert.ok(!html.includes('id="recipeLevelBonus"'), '食谱页不应再保留单一全局等级加成输入');
assert.ok(html.includes('id="personalSettingsDialog"'), '缺少统一个人设置侧栏');
assert.ok(html.includes('id="profileIslandBonuses"'), '个人设置缺少岛屿加成资料');
assert.ok(html.includes('id="profileIngredientStock"'), '个人设置缺少共用食材库存');
assert.ok(html.includes('id="profileRecipeList"'), '个人设置缺少逐食谱加成与完成状态');
assert.ok(html.includes('id="profileRecipeBulk" type="number" min="0" max="70"'), '食谱等级输入必须允许0表示未做过，并限制到Lv.70');
assert.ok(!html.includes('data-recipe-cooked'), '食谱是否做过不应保留独立开关');
assert.ok(html.includes('recipeEnergy:plannedRecipeEnergy'), '本周计划不得推荐食谱等级为0的未解锁料理');
assert.ok(html.includes('官方公告快照 · 2026-09-10'), '活动页资料快照未更新');
assert.ok(!html.includes('梦幻迷你拍照惊喜任务进行中'), '活动页仍把已经结束的梦幻拍照活动显示为进行中');
assert.ok(html.includes('超能力系主技能触发率 ×1.5'), '活动页缺少超梦活动的技能触发率细节');
assert.ok(html.includes('id="recipeIngredient" multiple'), '食谱页必须支持多食材交集筛选');
assert.ok(html.includes('id="recipeCookedFilter"'), '食谱页缺少未做过筛选');
assert.ok(html.includes('id="currentTeamDrawer"'), '当前队伍缺少切换侧栏');
assert.ok(html.includes('id="pokemonPickerDialog"'), '缺少可搜索的宝可梦图标选择器');
assert.ok(html.includes('id="selectionOddsTool"'), '本周作战页缺少友情徽章与严选概率小工具');
const weeklyMarkup=html.slice(html.indexOf('id="weeklyPlanner"'),html.indexOf('data-page="team"'));
assert.ok(weeklyMarkup.includes('id="selectionOddsTool"'), '友情徽章与严选概率应放在本周作战，而不是宝可梦盒子');
assert.ok(!html.includes('id="selectionOddsTool" data-page="box"'), '友情徽章与严选概率不应继续归属盒子页');
assert.ok(html.includes('id="weeklyActivityTools"'), '本周作战缺少按周模式显隐的活动设置容器');
assert.ok(html.includes('高级设置：道具与锅容量'), '本周作战道具设置不应被误写成活动周专用');
assert.ok(!html.includes('高级设置：活动周道具'), '本周作战仍保留了活动周专属的错误道具标题');
assert.ok(html.includes('id="selectionLockedGold"'), '严选概率工具缺少实际锁金格数');
assert.ok(html.includes('id="selectionGraduationRole"'), '严选概率工具缺少本站毕业定位选择');
assert.ok(html.includes('id="pokemonCompareRole"'), '个体生产对比缺少定位选择');
assert.ok(html.includes('<option value="berry">树果位（含树果骤增）</option>'), '树果骤增技能手必须明确归入树果位对比');
assert.ok(html.includes("title.dataset.noIngredientIcons=''"), '食谱名称必须显式禁止食材图标装饰');
assert.ok(html.includes('value="pokedex-asc">图鉴编号顺序'), '盒子默认排序必须提供图鉴编号顺序');
assert.ok(html.includes('data-k="pokedexId">图鉴'), '盒子表格第一列必须显示图鉴编号');
assert.ok(html.includes('data-k="speciesTierRank">种族梯级'), '盒子表格必须单独显示种族梯级列');
assert.ok(html.includes('data-k="scoreIndividual">个体质量'), '盒子表格必须单独显示个体质量列');
assert.ok(!html.includes('个人梯级表'), '种族梯级表头不应继续显示个人梯级表副标题');
assert.ok(!html.includes('梯级／个体质量'), '种族梯级与个体质量不应继续合并显示');
assert.ok(html.includes("button.append(number);\n    return bindScoreTooltip(button,mon,`${mon.name} 种族梯级"), '种族梯级卡片不应重复显示种族梯级文字');
assert.ok(html.includes('ingredientRouteCell(r)'), '三行食材路线应使用不带斜杠的独立行');
assert.ok(html.includes('natureCell(r.nature)'), '性格列必须使用名称与上下修正的分行展示');
assert.ok(html.includes("labels={speed:'帮忙',ingredient:'食材',skill:'技能',energy:'活力',exp:'EXP'}"), '性格修正必须使用统一短标签');
assert.ok(html.includes('value="species-tier-desc">种族梯级：高到低'), '盒子排序缺少种族梯级高到低');
assert.ok(html.includes('value="species-tier-asc">种族梯级：低到高'), '盒子排序缺少种族梯级低到高');
assert.ok(html.includes('id="pokemonCollectionIntent"'), '个体编辑器必须保留收藏状态');
assert.ok(!html.includes('id="pokemonCustomNumber"'), '个体编辑器不应继续显示无用途的自定义编号');
assert.ok(!html.includes('id="pokemonBox"'), '盒子归属应在盒子管理中维护，不应在个体编辑器重复显示');
assert.ok(!html.includes('id="pokemonBattleEligible"'), '实战资格应由培养矩阵判断，不应在个体编辑器重复显示');
assert.ok(html.includes('id="pokemonAllRounderFocusWrap" hidden'), '评分定位必须默认隐藏并仅对全能型开放');
assert.ok(html.includes('id="pokemonAllMightyWrap" hidden'), '技能选择必须默认隐藏并仅对梦幻开放');
assert.ok(pokemonManagerSource.includes("allMightyWrap.hidden=String(species.id)!=='151'"), '梦幻技能选择缺少物种条件');
assert.ok(pokemonManagerSource.includes("allRounderFocusWrap.hidden=species.specialty!=='all'"), '评分定位缺少全能型条件');
assert.ok(pokemonManagerCss.includes('.pokemon-editor-field[hidden]{display:none!important}'), '编辑器条件字段的 hidden 状态不得被 flex 样式覆盖');
assert.ok(html.includes('level-manager-evolution.css'), '等级更新弹窗缺少进化按钮样式');
assert.ok(html.includes("catalog:window.POKEMON_SLEEP_CATALOG,dataApi:window.POKEMON_SLEEP_DATA"), '等级更新器必须接收图鉴与持久化接口以执行进化');
assert.ok(levelManagerSource.includes("type:'evolution'"), '等级更新器缺少进化保存与页面重算通知');
assert.ok(!html.includes('id="pokemonPriority"'), '手工培养建议控件应移除，统一使用动态重算');
assert.ok(!html.includes('id="pokemonNote"'), '不再需要的个体备注控件应移除');
assert.ok(!html.includes('<th>备注</th>'), '盒子列表不应再展示备注列');
assert.ok(html.includes('class="box-multi-filter" id="rf"'), '定位筛选必须支持同组多选');
assert.ok(!html.includes('class="box-multi-filter" id="tf"'), '盒子主筛选不应继续展示物种梯级筛选');
assert.ok(!html.includes('class="box-multi-filter" id="ef"'), '盒子主筛选不应继续展示用途状态筛选');
assert.ok(!html.includes('data-k="boxId">盒子与用途'), '盒子主列表不应继续展示盒子与用途列');
assert.ok(!html.includes('value="tier-desc">梯级：S 到 C'), '盒子排序不应继续展示单独梯级排序');
assert.ok(!html.includes('value="species-desc"'), '盒子不应继续暴露种族分排序');
assert.ok(html.includes("pokemon-sleep:before-reload"), '个体保存前必须保留盒子筛选和滚动位置');
assert.ok(html.indexOf('all-rounder-rules.js') < html.indexOf('pokemon-scoring.js'), '动态评分必须在全能型规则加载后初始化');
assert.ok(html.indexOf('species-tiers.js') < html.indexOf('pokemon-scoring.js'), '动态评分必须在梯级表加载后初始化');

console.log(`site structure tests passed (${ids.length} ids, ${new Set(localRefs).size} local refs)`);
