'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const weekly = require('../weekly-planner.js');
const teamPlanner = require('../team-planner.js');
const cookingSuccess = require('../cooking-success.js');
const scoring = require('../pokemon-scoring.js');
const picker = require('../pokemon-picker.js');
const catalog = require('../pokemon-catalog.generated.js');

assert.equal(weekly.effectivePot(81, false), 81);
assert.equal(weekly.effectivePot(81, true), 122);
const monday=new Date(2026,7,31,12,0,0),sunday=new Date(2026,8,6,12,0,0);
assert.equal(weekly.weekKey(monday),'2026-08-31');
assert.equal(weekly.weekKey(sunday),'2026-08-31');
assert.equal(weekly.daysRemainingInWeek(monday),7);
assert.equal(weekly.daysRemainingInWeek(sunday),1);
const shifts=weekly.buildShiftSchedule(monday,24,4,1,2);
assert.equal(shifts.stepMinutes,15);
assert.ok(shifts.rows.length>=1);
assert.equal(shifts.segments.some(segment=>segment.kind==='prepare'),true);
assert.equal(shifts.segments.some(segment=>segment.kind==='tasty'),true);
assert.equal(shifts.segments.some(segment=>segment.kind==='output'),true);
assert.equal(shifts.segments.every((segment,index)=>index===0||segment.start>=shifts.segments[index-1].end),true,'换队表的时间段不能互相重叠');
const zoneShifts=weekly.buildShiftSchedule(monday,24,4,0,0,6);
assert.equal(zoneShifts.segments[0].kind,'berry-zone','超梦驻场必须固定排在周初');
const zoneTimeline=weekly.simulateBerryZoneStages([
  {kind:'berry-zone',hours:12,triggers:6,magoBerryEnergy:10000},
  {kind:'output',hours:156,triggers:0,magoBerryEnergy:100000}
],10,24,2);
assert.equal(zoneTimeline.endPct,22);
assert.equal(Math.round(zoneTimeline.bonusEnergy),23600,'领域应在超梦驻场期按平均层数、换下后按持续层数计算');
const cappedZone=weekly.simulateBerryZoneStages([{kind:'berry-zone',hours:24,triggers:20,magoBerryEnergy:10000}],0,24,2);
assert.equal(cappedZone.endPct,24);
assert.equal(cappedZone.capReached,true);
assert.ok(cappedZone.bonusEnergy<2400,'驻场中途才满层时不能把全段都按24%计算');

const normalized=weekly.normalizeState({recipeType:'坏数据',activityKey:'bad',islandIndex:99,mealGoal:80,weekKey:'2026-08-31',completedMeals:['d0-m0','bad'],penaltyLines:{'萌绿之岛':19563553}},['特选苹果'],9,monday);
assert.equal(normalized.recipeType,'咖喱／浓汤');
assert.equal(normalized.islandIndex,8);
assert.equal(normalized.mealGoal,21);
assert.deepEqual(normalized.completedMeals,['d0-m0']);
assert.equal(normalized.goodCamp,false,'旧版单一好露营券开关迁移后不应误算为准备周当前采集增益');
assert.equal(normalized.eventGoodCamp,true);
assert.equal(normalized.schemaVersion,12);
assert.equal(normalized.simulationDays,7);
assert.equal(normalized.simulationAutoTasty,true);
assert.equal(normalized.simulationTastyTarget,70);
assert.equal(normalized.skillCollectionHours,4);
assert.equal(normalized.collectBeforeSwitch,true);
assert.equal(normalized.exWeeklyEffect,'none');
assert.equal(Object.hasOwn(normalized,'simulationAutoPot'),false);
assert.equal(weekly.normalizeState({simulationTastyTarget:0},['特选苹果'],9,monday).simulationTastyTarget,0,'0%目标应能明确关闭爆锅蓄力');
assert.equal(normalized.currentSnorlaxStrength,0);
assert.equal(normalized.sleepType,'balanced');
assert.equal(normalized.sleepObjective,'combined');
assert.equal(normalized.sleepTargetId,'');
assert.equal(Object.hasOwn(normalized,'penaltyLines'),false,'旧版8只遇见参考线应从本地状态中清理');
assert.deepEqual(normalized.preparationRecipeTypes,['咖喱／浓汤','沙拉']);
const migratedSleepEnergy=weekly.normalizeState({schemaVersion:5,currentSnorlaxStrength:0,bedtimeSnorlaxStrength:5000000},['特选苹果'],9,monday);
assert.equal(migratedSleepEnergy.currentSnorlaxStrength,5000000,'旧版睡前能量应迁移为唯一的当前卡比兽能量');
assert.equal(Object.hasOwn(migratedSleepEnergy,'bedtimeSnorlaxStrength'),false,'迁移后不再保留第二个能量输入');
const nextWeek=weekly.normalizeState(normalized,['特选苹果'],9,new Date(2026,8,7,12,0,0));
assert.deepEqual(nextWeek.completedMeals,[]);
assert.deepEqual(nextWeek.mealHistory,[]);
assert.equal(nextWeek.berryZoneEnabled,false);
assert.equal(nextWeek.recipeRecommendationMode,'energy');

const recipes = [
  {id:1,name:'小料理',type:'沙拉',energy:1000,total:10,ingredients:[{name:'特选苹果',amount:10}]},
  {id:2,name:'大料理',type:'沙拉',energy:3000,total:20,ingredients:[{name:'特选苹果',amount:20}]},
  {id:3,name:'咖喱',type:'咖喱／浓汤',energy:5000,total:20,ingredients:[{name:'豆制肉',amount:20}]}
];
assert.equal(weekly.chooseTargetRecipe(recipes,'沙拉',15,{},{}).id,1);
assert.equal(weekly.chooseTargetRecipe(recipes,'沙拉',25,{'特选苹果':60},{'特选苹果':100}).id,2);
assert.equal(weekly.recipeRows(recipes,'沙拉',25,recipe=>recipe.id===1?5000:3000)[0].id,1,'食谱等级换算后的能量应参与排序');
assert.deepEqual(weekly.cookableRecipeRows(recipes,'沙拉',25,{'特选苹果':15}).map(recipe=>recipe.id),[1],'只能推荐库存足够完整制作的食谱');
assert.deepEqual(weekly.cookableRecipeRows(recipes,'沙拉',15,{'特选苹果':100}).map(recipe=>recipe.id),[1],'当前锅容量必须限制推荐');
const lockedRecipe={id:4,name:'未解锁苹果料理',type:'沙拉',energy:6000,total:5,ingredients:[{name:'特选苹果',amount:5}]};
assert.deepEqual(weekly.cookableRecipeRows([...recipes,lockedRecipe],'沙拉',25,{'特选苹果':15},recipe=>recipe.id===4?recipe.energy:0).map(recipe=>recipe.id),[4],'未解锁料理应能按Lv.1能量进入下一餐推荐');
const cooked=weekly.consumeRecipeIngredients({'特选苹果':25,'萌绿玉米':4},recipes[1]);
assert.equal(cooked.ok,true);
assert.deepEqual(cooked.inventory,{'特选苹果':5,'萌绿玉米':4},'勾选做菜只扣除固定配方食材');
const notCooked=weekly.consumeRecipeIngredients({'特选苹果':19},recipes[1]);
assert.equal(notCooked.ok,false);
assert.deepEqual(notCooked.inventory,{'特选苹果':19},'库存不足时不得部分扣料');
assert.deepEqual(weekly.recipeCompletionPatch({'特选苹果':8},lockedRecipe,{recipeLevels:{'1':20}}),{ingredientStock:{'特选苹果':8},recipeLevels:{'1':20,'4':1}},'首次做未解锁食谱时应同时登记为Lv.1');
assert.deepEqual(weekly.recipeCompletionPatch({'特选苹果':8},recipes[0],{recipeLevels:{'1':20}}),{ingredientStock:{'特选苹果':8}},'已解锁食谱不应重置现有等级');
assert.deepEqual(weekly.restoreRecipeIngredients({'特选苹果':5},{'特选苹果':20},800),{ok:true,inventory:{'特选苹果':25},restored:{'特选苹果':20},overflow:0},'撤销料理必须原样退回食材');
assert.equal(weekly.restoreRecipeIngredients({'特选苹果':790},{'特选苹果':20},800).ok,false,'撤销不得静默突破仓库硬上限');
assert.deepEqual(weekly.recipeUndoPatch({'特选苹果':25},{recipeId:'4',previousRecipeLevel:0},{recipeLevels:{'1':20,'4':1}}),{ingredientStock:{'特选苹果':25},recipeLevels:{'1':20}},'撤销首次料理必须恢复为未解锁');
assert.deepEqual(weekly.rankRecipeRecommendations([...recipes,lockedRecipe],'沙拉',25,{'特选苹果':25},recipe=>recipe.energy,{mode:'unlock',isUnlocked:recipe=>recipe.id!==4}).map(row=>row.recipe.id),[4,2,1],'解锁优先模式应把可做的未解锁食谱放到最前');
assert.equal(weekly.ACTIVITY_PROFILES.snapshot.archived,true);
assert.equal(weekly.ACTIVITY_PROFILES.mewtwo1.ingredientHelpBonus,1);
assert.equal(weekly.ACTIVITY_PROFILES.mewtwo1.skillTriggerMultiplier,1.5);
assert.equal(weekly.ACTIVITY_PROFILES.mewtwo2.sleepDrowsyPowerMultiplier,1.3);
assert.equal(weekly.ACTIVITY_PROFILES.mewtwo2.archived,true);
assert.equal(weekly.ACTIVITY_PROFILES.goodSleep39.universalSleepMultiplier,1.5);
assert.equal(weekly.ACTIVITY_PROFILES.cooking125.cookingEnergyMultiplier,1.25);
assert.equal(weekly.WEEK_MODE_VIEWS.normal.showSimulation,false);
assert.equal(weekly.WEEK_MODE_VIEWS.preparation.showRoutes,true);
assert.equal(weekly.WEEK_MODE_VIEWS.event.showSimulation,true);
assert.equal(weekly.WEEK_MODE_VIEWS.normal.showHunt,true);
assert.equal(weekly.WEEK_MODE_VIEWS.preparation.showHunt,true);
assert.equal(weekly.WEEK_MODE_VIEWS.event.showHunt,true);
assert.equal(weekly.calculateDrowsyPower(200000,50,1.1),11000000);
assert.deepEqual(weekly.sleepMultiplierForTeam(weekly.ACTIVITY_PROFILES.mewtwo1,[{name:'梦幻'}],true),{multiplier:1.1,active:true,matched:'梦幻',required:['梦幻','超梦']});
assert.deepEqual(weekly.sleepMultiplierForTeam(weekly.ACTIVITY_PROFILES.goodSleep39,[],true),{multiplier:1.5,active:true,matched:'全队',required:[]});
assert.equal(weekly.sleepMultiplierForTeam(weekly.ACTIVITY_PROFILES.mewtwo1,[{name:'梦幻'}],false).multiplier,1,'非活动岛不能套用活动睡意之力倍率');
const singleSleep=weekly.calculateSleepPlan({area:'萌绿之岛',currentStrength:100000,bedtimeStrength:150000,sleepType:'balanced',objective:'combined'});
assert.equal(singleSleep.recommendation,'single');
assert.equal(singleSleep.single.sessions[0].score,100);
const splitSleep=weekly.calculateSleepPlan({area:'萌绿之岛',currentStrength:4000000,bedtimeStrength:5000000,sleepType:'balanced',objective:'combined'});
assert.equal(splitSleep.recommendation,'split');
assert.equal(splitSleep.bestSplit.sessions.reduce((sum,session)=>sum+session.score,0),100);
assert.ok(splitSleep.bestSplit.objectiveValue>splitSleep.single.objectiveValue,'应直接比较奖励曲线，而不是把8只遇见门槛当惩罚线');
const oneInputSleep=weekly.calculateSleepPlan({area:'萌绿之岛',currentStrength:5000000,sleepType:'balanced',objective:'combined'});
assert.equal(oneInputSleep.available,true);
assert.equal(oneInputSleep.bedtimeStrength,5000000,'只输入当前能量时应自动用于两次研究');
assert.deepEqual(weekly.applyActivityContext({island:{name:'萌绿之岛'},berries:['金枕果','芒芒果','莓莓果']},weekly.ACTIVITY_PROFILES.mewtwo1).berries,['芒芒果','金枕果','莓莓果']);
assert.equal(weekly.activityApplies(weekly.ACTIVITY_PROFILES.mewtwo1,{island:{name:'宝蓝湖畔'}}),false);
assert.equal(weekly.activityApplies(weekly.ACTIVITY_PROFILES.cooking125,{island:{name:'宝蓝湖畔'}}),true,'未限制岛屿的活动配置应能通用于所有岛屿');
assert.deepEqual(weekly.activityMemberModifier(weekly.ACTIVITY_PROFILES.mewtwo1,true)({berry:'芒芒果'}),{ingredientHelpBonus:1,skillTriggerMultiplier:1.5,mainSkillLevelBonus:2,label:'超梦登场活动·第1周（已结束）'});
assert.deepEqual(weekly.activityMemberModifier(weekly.ACTIVITY_PROFILES.mewtwo1,false)({berry:'芒芒果'}),{});
const mergedRoutes=weekly.mergeTargetRecipes([
  {id:'salad',name:'沙拉A',type:'沙拉',ingredients:[{name:'特选苹果',amount:10},{name:'萌绿玉米',amount:5}]},
  {id:'curry',name:'咖喱A',type:'咖喱／浓汤',ingredients:[{name:'特选苹果',amount:6},{name:'豆制肉',amount:8}]}
]);
assert.deepEqual(Object.fromEntries(mergedRoutes.ingredients.map(item=>[item.name,item.amount])),{'特选苹果':10,'萌绿玉米':5,'豆制肉':8},'双路线共同食材应取较高需求而不是相加');

const budget=weekly.ingredientBudget(recipes[1],{'特选苹果':30},{'特选苹果':0},15,5,7);
assert.equal(budget.remaining,10);
assert.equal(budget.rows[0].need,200);
assert.equal(budget.rows[0].projectedGap,0);
assert.equal(budget.rows[0].daysToStock,6.7);
const impossible=weekly.ingredientBudget(recipes[1],{'特选苹果':5},{'特选苹果':0},15,0,2);
assert.ok(impossible.projectedShortages.length>0);
const capped=weekly.ingredientBudget(recipes[1],{'特选苹果':30},{'豆制肉':760,'特选苹果':0},15,0,7);
assert.equal(capped.inventoryLimit,800);
assert.equal(capped.batchMeals,2,'只应规划仓库剩余40格能容纳的两餐');
assert.equal(capped.rows[0].need,40);
assert.ok(capped.rows.reduce((sum,row)=>sum+row.need,0)+760<=800,'下一批阈值不得超过仓库硬上限');
const full=weekly.ingredientBudget(recipes[1],{'特选苹果':30},{'豆制肉':800,'特选苹果':0},15,0,7);
assert.equal(full.batchMeals,0);
assert.ok(weekly.createActionPlan(full,recipes[1],{production:{}},{production:{}},monday,{weekMode:'preparation'}).title.includes('仓库已满'));

const projectRoot = path.resolve(__dirname,'..');
const html = fs.readFileSync(path.join(projectRoot,'index.html'),'utf8');
const weeklySource = fs.readFileSync(path.join(projectRoot,'weekly-planner.js'),'utf8');
assert.ok(html.includes('id="weeklyCurrentStrength"'));
assert.ok(html.includes('id="weeklySleepTarget"'));
assert.ok(html.includes('id="weeklySimulationDays"'));
assert.ok(html.includes('id="weeklySimulationAutoTasty"'));
assert.ok(html.includes('id="weeklySimulationTastyTarget"'));
assert.ok(html.includes('id="weeklySkillCollectionHours"'));
assert.ok(html.includes('id="weeklyCollectBeforeSwitch"'));
assert.ok(html.includes('id="weeklyExEffect"'));
assert.ok(html.includes('活动周完整推演器'));
assert.ok(html.includes('<option value="pokemon">指定宝可梦出现</option>'));
assert.ok(!html.includes('id="weeklyBedtimeStrength"'),'本周作战页面只应要求一个当前卡比兽能量');
assert.ok(weeklySource.includes("section.dataset.noIngredientIcons=''"),'周目标中的食谱路线必须禁止把食材词误装饰成图标');
assert.ok(!weeklySource.includes('name.append(icon(row.name),document.createTextNode(row.name))'),'食材图标组件已经包含名称，不得再追加一遍名称');
assert.ok(!weeklySource.includes('copy.innerHTML=`<b>${row.name}</b><small>每餐 ${row.perMeal}</small>`'),'备料卡不得在食材图标组件旁重复输出食材名');
const legacyFixture=path.join(projectRoot,'scripts','legacy-box-fixture.txt');
const syntheticBox=[
  '1|妙蛙花|2200|50|否|甜甜蜜×2／甜甜蜜×5／好眠番茄×7|39:00|30|食材获取S Lv.3|帮手奖励；食材概率M；帮忙速度S；持有上限M；技能概率S|认真|继续使用|',
  '2|水箭龟|2100|50|否|哞哞鲜奶×2／哞哞鲜奶×5／放松可可×7|40:00|30|食材获取S Lv.3|食材概率M；帮手奖励；帮忙速度S；持有上限M；技能概率S|认真|继续使用|',
  '3|火爆兽|2000|50|否|暖暖姜×1／暖暖姜×2／火辣香草×3|33:00|25|能量填充S Lv.3|树果数量S；帮忙速度M；帮手奖励；技能概率S；持有上限M|认真|继续使用|',
  '4|雷丘|1900|50|否|特选苹果×1／特选苹果×2／暖暖姜×3|32:00|25|能量填充S Lv.3|树果数量S；帮忙速度M；帮手奖励；技能概率S；持有上限M|认真|继续使用|',
  '5|沙奈朵|1800|50|否|特选苹果×1／特选苹果×2／粗枝大葱×2|37:00|25|活力全体疗愈S Lv.6|帮手奖励；技能概率M；帮忙速度S；技能概率S；持有上限M|认真|继续使用|'
].join('\n');
const raw = fs.existsSync(legacyFixture)&&process.env.POKEMON_SLEEP_TEST_SYNTHETIC!=='1'?fs.readFileSync(legacyFixture,'utf8').trim():syntheticBox;
const columns = ['id','name','sp','lv','shiny','ingredients','interval','inv','main','subs','nature','priority','note'];
const box = raw.split(/\r?\n/).map(line=>Object.fromEntries(line.split('|').map((value,index)=>[columns[index],value||''])));
const berryNames=['柿仔果','苹野果','橙橙果','萄葡果','金枕果','莓莓果','樱子果','零余果','勿花果','椰木果','芒芒果','木子果','文柚果','墨莓果','番荔果','异奇果','靛莓果','桃桃果'];
box.forEach(mon=>{const species=scoring.recordForPokemon(mon);mon.specialty=species.specialty;mon.specialtyLabel={berry:'树果手',ingredient:'食材手',skill:'技能手',all:'全能手'}[mon.specialty];mon.berry=berryNames[species.berryId-1];mon.battleEligible=true});
const context={};context.window=context;context.globalThis=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(projectRoot,'recipes.js'),'utf8'),context);
const realRecipes=context.POKEMON_SLEEP_RECIPES.map(recipe=>({...recipe,total:recipe.ingredients.reduce((sum,item)=>sum+item.amount,0)}));
const islandContext={island:{name:'宝蓝湖畔',kind:'普通岛'},index:4,berries:['金枕果','芒芒果','樱子果'],expert:false};
const outputScore=mon=>Number(mon.sp)||100;
const healer=mon=>/活力全体疗愈|新月祈祷/.test(mon.main);
const special=mon=>['梦幻','雷公','炎帝','水君','拉帝亚斯','拉帝欧斯','克雷色利亚','达克莱伊'].includes(mon.name);
const recommend=()=>{const heal=box.filter(healer).sort((a,b)=>outputScore(b)-outputScore(a))[0],producers=box.filter(mon=>!healer(mon)&&!special(mon)).sort((a,b)=>outputScore(b)-outputScore(a)).slice(0,4);return {regular:{ids:[...producers.map(mon=>mon.id),heal.id],label:'无特殊宝可梦'}}};
const currentProduction=Object.fromEntries(box.map(mon=>{const species=scoring.recordForPokemon(mon);return [mon.id,{ingredientRate:species.ingredientRate,baseBerryCount:species.baseBerryCount}]}));
const common={pokemon:box,context:islandContext,recommendTeams:recommend,individualProductionScore:outputScore,isFullTeamHealer:healer,isSpecialPokemon:monId=>special(box.find(mon=>String(mon.id)===String(monId))||{}),planner:teamPlanner,production:currentProduction,goodCamp:true,activityKey:'snapshot',recipes:realRecipes,recipeType:'沙拉',basePot:81,mealGoal:15,completedMeals:[],inventory:{},now:monday};
const target=weekly.recipeRows(realRecipes,'沙拉',121)[0];
const realPlan=weekly.calculatePlan({...common,targetRecipeId:target.id});
assert.equal(realPlan.preparationTeam.members.length,5);
assert.equal(realPlan.outputTeam.members.length,5);
assert.equal(realPlan.targetRecipe.id,target.id);
assert.equal(realPlan.budget.goal,15);
assert.ok(realPlan.budget.rows.length>0);
assert.ok(['prepare','adjust','output'].includes(realPlan.action.phase));
assert.ok(Number(realPlan.action.collectionHours)>0);
assert.equal(realPlan.weekMode,'normal');
assert.equal(realPlan.simulations.length,0,'普通周不应提前生成活动周推演');
const realEventPlan=weekly.calculatePlan({...common,targetRecipeId:target.id,weekMode:'event'});
assert.equal(realEventPlan.simulations.length,1);
assert.equal(realEventPlan.simulations[0].teamSettings.favoriteBerries.join('／'),islandContext.berries.join('／'),'活动周推演必须把本周实际喜爱树果传给队伍能量引擎');
const cookingSimulation=weekly.simulateActivityWeek({...common,activity:weekly.ACTIVITY_PROFILES.cooking125,targetRecipe:recipes[0],days:1,mealGoal:1,inventory:{'特选苹果':20},recipeEnergy:()=>1000,islandBonusPct:50,islandProfile:'lapis',autoTasty:false,currentSnorlaxStrength:12345});
assert.equal(cookingSimulation.available,true);
assert.equal(cookingSimulation.cookedMeals,1);
assert.equal(cookingSimulation.mealEnergy,1375,'活动料理倍率与工作日自然10%大成功率必须共同进入每餐期望能量');
assert.equal(cookingSimulation.cookingEnergy,1375);
assert.equal(cookingSimulation.startingEnergy,12345);
assert.equal(cookingSimulation.teamSettings.islandBonusPct,50);
assert.ok(cookingSimulation.stages.reduce((sum,stage)=>sum+stage.hours,0)<=24.01,'准备、爆锅与输出队必须共享同一推演时长，不能重复计算时间');
assert.ok(cookingSimulation.stages.every(stage=>stage.scheduleText),'每个阶段都应给出可执行的日期时间说明');
assert.ok(cookingSimulation.prepareHoursWithoutStock>=cookingSimulation.stockSavedPrepareHours,'库存节省时长必须来自零库存反事实对照');
const outputOnlyStage=cookingSimulation.stages.find(stage=>stage.kind==='output');
assert.ok(outputOnlyStage&&outputOnlyStage.breakdown,'活动周最终阶段必须保留共享队伍引擎的逐项审计结果');
const directOutput=teamPlanner.calculateTeam(outputOnlyStage.team,common.production,{goodCamp:true,energyProfile:'timeline',memberModifier:weekly.activityMemberModifier(weekly.ACTIVITY_PROFILES.cooking125,true),durationHours:outputOnlyStage.hours,islandBonusPct:50,islandProfile:'lapis',favoriteBerries:islandContext.berries,startEnergy:100,sleepScore:100,skillCollectionHours:4,collectBeforeSwap:true,exWeeklyEffect:'none'});
assert.deepEqual(outputOnlyStage.breakdown,weekly.teamBreakdown(directOutput),'同一五人和同一设置在当前队伍与活动推演中必须逐项完全一致');
assert.ok(Math.abs(cookingSimulation.ingredientRows[0].produced-(outputOnlyStage.breakdown.ingredients['特选苹果']||0))<.11,'活动周食材结算必须采用精确阶段结果，而不是早期线性估算');
const mewtwo={...box[0],id:'mewtwo-box',name:'超梦',nickname:'测试超梦',speciesId:'150',finalFormId:'150',specialty:'skill',specialtyLabel:'技能手',berry:'芒芒果',berryId:11,lv:'70',interval:'38:20',catalogHelpFrequencyBaseSec:2300,inv:'24',ingredientRate:.16,skillRatePct:2.9,mainSkillId:40,main:'精神击破（树果领域）Lv.6',ingredients:'萌绿大豆×1／萌绿玉米×2／窝心洋芋×3',subs:'技能概率M；帮忙速度M；技能概率S；帮手奖励；持有上限L',nature:'慎重：技能↑ 食材↓'};
const zoneSimulation=weekly.simulateActivityWeek({...common,pokemon:[...box,mewtwo],isSpecialPokemon:id=>id==='mewtwo-box'||special(box.find(mon=>String(mon.id)===String(id))||{}),activity:weekly.ACTIVITY_PROFILES.normal,targetRecipe:recipes[0],days:7,mealGoal:1,inventory:{'特选苹果':20},recipeEnergy:()=>1000,autoTasty:false,berryZoneEnabled:true,berryZoneMewtwoId:'mewtwo-box',berryZoneStartPct:0,berryZoneDeployHours:72,berryZoneAutoSwap:true});
assert.equal(zoneSimulation.berryZone.enabled,true);
assert.equal(zoneSimulation.stages[0].kind,'berry-zone');
assert.ok(zoneSimulation.berryZone.expectedTriggers>0);
assert.ok(zoneSimulation.berryZone.zoneBonusEnergy>0);
assert.ok(zoneSimulation.berryZone.endPct<=24);
assert.ok(zoneSimulation.stages.reduce((total,stage)=>total+stage.hours,0)<=168.01,'超梦驻场必须占用整周时长，不能额外叠加');
const persistedZoneSimulation=weekly.simulateActivityWeek({...common,activity:weekly.ACTIVITY_PROFILES.normal,targetRecipe:recipes[0],days:1,mealGoal:1,inventory:{'特选苹果':20},recipeEnergy:()=>1000,autoTasty:false,berryZoneEnabled:true,berryZoneStartPct:12});
assert.equal(persistedZoneSimulation.berryZone.enabled,true,'换下超梦后应允许只计算已有领域');
assert.equal(persistedZoneSimulation.stages.some(stage=>stage.kind==='berry-zone'),false);
assert.equal(persistedZoneSimulation.berryZone.endPct,12);
const eventContext={...islandContext,island:{name:'萌绿之岛',kind:'普通岛'},berries:['金枕果','莓莓果','樱子果']};
const eventSimulation=weekly.simulateActivityWeek({...common,context:eventContext,activity:weekly.ACTIVITY_PROFILES.mewtwo1,targetRecipe:recipes[0],days:1,mealGoal:1,inventory:{'特选苹果':20},recipeEnergy:()=>1000,islandBonusPct:35,islandProfile:'none',autoTasty:false});
const eventStage=eventSimulation.stages.find(stage=>stage.kind==='output'),eventTeam=eventStage.team.map(mon=>({...mon,inv:String((Number(mon.inv)||0)+weekly.ACTIVITY_PROFILES.mewtwo1.carryBonus)})),eventSettings=eventSimulation.teamSettings;
const directEvent=teamPlanner.calculateTeam(eventTeam,common.production,{goodCamp:true,energyProfile:'timeline',memberModifier:weekly.activityMemberModifier(weekly.ACTIVITY_PROFILES.mewtwo1,true),durationHours:eventStage.hours,...eventSettings});
assert.deepEqual(eventStage.breakdown,weekly.teamBreakdown(directEvent),'活动持有、技能等级／概率、食材帮忙与喜爱树果也必须和当前队伍共享口径');
const fakeTastyPlanner={...teamPlanner,calculateTastyDeployment(){return {reachable:true,estimate:{safeHours:1,state:cookingSuccess.initialBonusState(70)},tastyTeam:{team:[box[0]],result:{energy:{durationHours:24,totalEnergy:0},ingredients:[]}}}}};
const tastySimulation=weekly.simulateActivityWeek({...common,planner:fakeTastyPlanner,activity:weekly.ACTIVITY_PROFILES.normal,targetRecipe:recipes[0],days:1,mealGoal:1,inventory:{'特选苹果':20},recipeEnergy:()=>100000,autoTasty:true,tastyTargetPct:70});
assert.equal(tastySimulation.tastyMeals,1,'高能量料理应选择料理成功 S 爆锅队');
assert.equal(tastySimulation.stages.some(stage=>stage.kind==='tasty'),true);
assert.ok(tastySimulation.cookingEnergy>110000,'爆锅餐应高于只计自然大成功率的料理期望');
const oversizedRecipe={id:99,name:'扩锅测试料理',type:'沙拉',energy:5000,total:100,ingredients:[{name:'特选苹果',amount:100}]};
const oversizedPlan=weekly.calculatePlan({...common,recipes:[...recipes,oversizedRecipe],targetRecipeId:99,basePot:81,goodCamp:false,simulationAutoTasty:false,weekMode:'event'});
assert.equal(oversizedPlan.targetRecipe.id,99,'手动指定的大锅食谱不能在进入扩锅判断前被当前锅容量过滤掉');
assert.equal(oversizedPlan.simulations[0].needsPot,true);
assert.equal(oversizedPlan.simulations[0].cookedMeals,0);
assert.ok(oversizedPlan.simulations[0].warnings.some(text=>text.includes('爆锅队')&&text.includes('不会增加容量')));
const sleepGatedPlan=weekly.calculatePlan({...common,targetRecipeId:target.id,currentSnorlaxStrength:5000000,sleepType:'balanced',sleepObjective:'combined'});
assert.equal(sleepGatedPlan.currentSleepEnergy,5000000);
assert.equal(sleepGatedPlan.sleepThresholdReached,true);
assert.equal(sleepGatedPlan.sleepPlan.currentStrength,5000000);
assert.equal(sleepGatedPlan.sleepPlan.bedtimeStrength,5000000,'两次研究默认都应使用用户输入的当前能量');
const belowSleepLine=weekly.calculatePlan({...common,targetRecipeId:target.id,currentSnorlaxStrength:1000000,sleepType:'balanced',sleepObjective:'combined'});
assert.equal(belowSleepLine.sleepThresholdReached,false);
assert.equal(belowSleepLine.sleepPlan.available,false,'未达到惩罚线时不应生成分段方案');
const targetSleepBelowLine=weekly.calculatePlan({...common,targetRecipeId:target.id,currentSnorlaxStrength:1000000,sleepType:'balanced',sleepObjective:'pokemon',sleepTargetId:'282'});
assert.equal(targetSleepBelowLine.sleepThresholdReached,false);
assert.equal(targetSleepBelowLine.sleepTarget.id,'282');
assert.equal(targetSleepBelowLine.sleepPlan.available,true,'指定严选目标不应被研究奖励惩罚线拦截');
assert.equal(targetSleepBelowLine.sleepPlan.target.pokemonName,'拉鲁拉丝');
const unavailableTarget=weekly.calculatePlan({...common,targetRecipeId:target.id,currentSnorlaxStrength:1000000,sleepType:'balanced',sleepObjective:'pokemon',sleepTargetId:'392'});
assert.equal(unavailableTarget.sleepPlan.available,false);
assert.ok(unavailableTarget.sleepPlan.reason.includes('不会在当前岛屿出现'));
const preparationPlan=weekly.calculatePlan({...common,targetRecipeId:target.id,weekMode:'preparation'});
assert.ok(preparationPlan.action.title.includes('活动前储备')||preparationPlan.action.phase==='adjust');
const preparationWithoutCurrentCamp=weekly.calculatePlan({...common,activityKey:'normal',targetRecipeId:target.id,goodCamp:false,eventGoodCamp:true,weekMode:'preparation'});
const preparationWithCurrentCamp=weekly.calculatePlan({...common,activityKey:'normal',targetRecipeId:target.id,goodCamp:true,eventGoodCamp:true,weekMode:'preparation'});
const totalPreparationIngredients=plan=>Object.values(plan.preparationTeam.daily).reduce((sum,value)=>sum+Number(value||0),0);
assert.equal(preparationWithoutCurrentCamp.pot,preparationWithCurrentCamp.pot,'准备周的未来目标锅只应读取活动周计划好露营券');
assert.ok(totalPreparationIngredients(preparationWithCurrentCamp)>totalPreparationIngredients(preparationWithoutCurrentCamp),'准备周的当前备料产出应读取本周好露营券');
const dualRoutePlan=weekly.calculatePlan({...common,goodCamp:false,eventGoodCamp:true,weekMode:'preparation',preparationRecipeTypes:['咖喱／浓汤','沙拉'],travelTicketPlanned:true});
assert.equal(dualRoutePlan.pot,122,'准备周目标锅应读取活动周计划好露营券，并按最终容量四舍五入');
assert.equal(dualRoutePlan.targetRecipes.length,2);
assert.ok(dualRoutePlan.targetRecipe.name.includes('双路线储备'));
assert.ok(dualRoutePlan.action.detail.includes('移动营地券'));
assert.equal(dualRoutePlan.simulations.length,0,'准备周只负责储备目标，不应提前显示或生成活动周推演');
const huntTargets=weekly.buildHuntTargets([{id:'x',name:'大竺葵',specialty:'berry',subs:'树果数量S；帮手奖励；帮忙速度M；研究EXP奖励；睡眠EXP奖励',nature:'固执：速度↑ 食材↓',scoreIndividual:88,scoreTotal:82,scoreBreakdown:{finalFormId:'154'}}],'宝蓝湖畔');
assert.equal(huntTargets.find(row=>row.id==='154').status,'covered');
assert.equal(huntTargets.find(row=>row.id==='254').status,'missing');
assert.ok(huntTargets.find(row=>row.id==='154').minimum.includes('Lv.50'));
assert.deepEqual(Object.fromEntries(huntTargets.map(row=>[row.id,row.name])),{
  '154':'大竺葵','254':'蜥蜴王','392':'烈焰猴','282':'沙奈朵'
});
const swampertTarget={id:'260',name:'巨沼怪',best:{speciesId:'259',name:'沼跃鱼'}};
assert.deepEqual(weekly.huntTargetIconIdentity(swampertTarget),{speciesId:'260',name:'巨沼怪'},'严选目标图标应表示目标最终形态，而非盒内当前最好个体');
assert.ok(picker.iconUrl(weekly.huntTargetIconIdentity(swampertTarget),catalog).endsWith('/260.png'));

const wrongArea=weekly.calculatePlan({...common,activityKey:'mewtwo1'});
assert.equal(wrongArea.preparationTeam.carryBonus,0);
const eventArea=weekly.calculatePlan({...common,context:{...islandContext,island:{name:'萌绿之岛',kind:'普通岛'}},activityKey:'mewtwo1'});
assert.equal(eventArea.preparationTeam.carryBonus,8);
assert.equal(eventArea.context.berries[0],'芒芒果','超梦活动周必须固定芒芒果为喜爱树果');
const completed=weekly.calculatePlan({...common,targetRecipeId:target.id,completedMeals:weekly.DAY_NAMES.flatMap((_day,day)=>weekly.MEAL_NAMES.map((_meal,meal)=>`d${day}-m${meal}`)).slice(0,15)});
assert.equal(completed.action.phase,'complete');
assert.equal(completed.budget.remaining,0);

console.log('weekly planner tests passed');
